using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using DataGateMonitor.Models;

namespace DataGateMonitor.DataBase.ConfigurationModels;

public abstract class BaseEntityConfiguration<T, TKey> : IEntityTypeConfiguration<T>
    where T : BaseEntity<TKey>
{
    public virtual void Configure(EntityTypeBuilder<T> entity)
    {
        entity.HasKey(e => e.Id);

        switch (Type.GetTypeCode(typeof(TKey)))
        {
            case TypeCode.Int32:
            case TypeCode.Int64:
                // PostgreSQL: GENERATED BY DEFAULT AS IDENTITY
                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd();
                break;

            case TypeCode.Object when typeof(TKey) == typeof(Guid):
                // If you're using PostgreSQL and want the database to generate UUIDs,
                // uncomment the following lines:
                //
                // entity.Property(e => e.Id)
                //       .HasDefaultValueSql("uuid_generate_v4()")
                //       .ValueGeneratedOnAdd();
                //
                // Otherwise, if you're generating the Guid in C# (e.g. Guid.NewGuid()),
                // you don't need to configure anything here.
                break;

            default:
                throw new NotSupportedException($"Unsupported key type: {typeof(TKey).Name}");
        }

        entity.Property(e => e.CreateDate)
            .IsRequired()
            .HasDefaultValueSql("CURRENT_TIMESTAMP");

        entity.Property(e => e.LastUpdate)
            .IsRequired()
            .HasDefaultValueSql("CURRENT_TIMESTAMP");
    }
}